[package]
name = "hello-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }